# Generated by Django 2.1.5 on 2019-02-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_auto_20190131_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='movimento',
            field=models.CharField(blank=True, choices=[('e', 'entrada'), ('s', 'saida')], max_length=1),
        ),
    ]
