# Generated by Django 2.1.5 on 2019-02-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_auto_20190201_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='saldo',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
